### PR TITLE
Useful functions for procedural mask layout

### PR DESCRIPTION
**Pull request by thomaslima**
All this code is additive to the current SiEPIC/utils module. I have coded tested and improved many polygon generation algorithms, such as arcs, sections, bezier waveguides, paths with varying widths, polygon resizing, automatic routing from port array to port array.

This code duplicates in functionality some of the code in SiEPIC/utils/__init__.py, but hopefully with some improvement. I hope that other SiEPIC developers can join in, refactor their code, and make use of these improvements.

Two main innovations:

1 Many polygon layout use a `ex` parameter that defines the unit vector in the x-axis. For example:
``` python
ex = pya.DVector(1,0)
ey = rotate90(ex)

# this will compute a point in coordinates (3,4) in any rotated reference frame.
p = 3 * ex + 4 * ey
```

This is very useful to de-duplicate code.

2 Included `KLayoutPCell` which is a bread-and-butter wrapper of Klayout's `pya.PCellDeclarationHelper`. For compatibility with current GUI-oriented SiEPIC, it can be converted to a `pya.PCellDeclarationHelper`-type cell and added to the tech/PDK library. But in procedural layout it adds two main functionalities:
    - Returns port positions when drawn. Can be placed a posteriori depending on these positions. This is important because the port positions will change depending on the parameters of the PCell.
    - Can be cached with the @cache_cell decorator. This means that if the pcell was previously instantiated with the same parameters, then the layout and port positions will be retrieved from a file in the disk. This speeds up large-scale mask-generation scripts.

### CODE REVIEW

**Comment by thomaslima** [comment]
**Warning**
All my colleagues use klayout with python >=3.6 installed, so I was generous with my use of python3.6 functionalities, such as f-strings. This code needs some refactoring if it is to be compatible with python2, or python3 < 3.6.
I've allowed edits from maintainers in this pull request. Feel free to commit to it!
Only merge this if the issue above is resolved.

**Comment by lukasc-ubc** [comment]
wow, lots of improvements.  the timing is good as we are presently developing a PDK for the new foundry, AMF.  I'll go through this hopefully this week.

**Comment by lukasc-ubc** [comment]
do we need to worry about backwards compatibility?

**Comment by thomaslima** [comment]
Nice!
It depends on whether you've already been using the modules I created inside utils. If not, then there will be no backwards compatibility issue since I've only added code and barely edited the original `utils.py`, now `utils/__init__.py`.

**Comment by jaspreetj** [comment]
Great work @thomaslima , I like the capabilities that you have added to the SiEPIC tools package. I am still reviewing the edits. 

What is the clustering for? is it for creating a parent pcell from a bunch of native or library specific pcells?

**Comment by thomaslima** [comment]
@jaspreetj No. Clustering works with Port objects, defined in geometry.py. It helps with channel routing between two port arrays.

**Comment by thomaslima** [comment]
Hey guys. let me know whether you plan to merge this into your repo. I'm also thinking of making a python package with these tools as standalone, to be called directly from python and bypassing all the Qt-bindings in SiEPIC-tools.

**Comment by thomaslima** [comment]
Great! I heard you were very busy. Another question: as klayout as a python module will soon be released, do you plan to refactor SiEPIC-Tools and the PDKs as a python module as well? It is entirely possible but it requires some refactoring. E.g. https://github.com/lightwave-lab/SiEPIC-Tools/pull/1

If you plan to do this I can muster some students to help from Princeton. If this is done and I can do the following, the SiEPIC pdks + tools will probably be the most powerful ones (for large scale masks at least) and hopefully will be adopted by more people. It will be more like nazca but with klayout as an engine, and siepic with dual functionality of containing layout algorithms and helping graphical layout in klayout. Not to mention that difficult and time consuming algorithms can be implemented in C and added to klayout's source code as a bridge. Think numpy.

``` python
import klayout
import siepic_tools
import siepic_ebeam_pdk
import very_large_library_of_pcells_from_princeton
import awesome_autorouting_algorithms

# code that makes a mask here

klayout.db.write('mask_v1.gds')
```

**Comment by lukasc-ubc** [comment]
Hi Thomas, @thomaslima @jaspreetj

In response to: https://github.com/lightwave-lab/SiEPIC-Tools/blob/lightwave/SiEPIC-Tools%20refactoring.md

I created a new branch, v0.4.0, to begin the large project of refactoring.  I moved your pull request to that branch so we can leave the v0.3.x alone for those that currently use it, and to use all your updates towards a major release.  Does that sound good?  We can work on the v0.4.0 branch between now and Dec 1st, then around then, move it back to master, and in KLayout Package manager point to the new v0.4.0…

How have you been using KLayout / SiEPIC-Tools lately?  Do you run it within KLayout, or are you now able to run externally?  In other words, have you done enough refactoring to make it work externally, or is that more of a wish at this stage?

class KLayoutPCell(object): you have examples of PCells?  in SiEPIC_IME_Lightwave there is a ring filter, but I think it is outdated compared to the new one. Do you have any in EBeam too?  I think it would be good to refactor some of the EBeam cells (since it is a public library), and provide a guideline of how people should create PCells from now.  And also procedural layout examples.  Hopefully it isn’t complicated.

We now have an AMF PDK and Library (two separate repositories), based on SiEPIC_IME.  Layer tables are different, and we have AMF’s PDK (their components) loaded in.

I am also wondering if Matthias at KLayout should be involved. For example, your KLayoutPCell, and class IMECell(object), really are creating building on top of Matthias did, rather than fixing it directly.  Are we creating too many layers of complexity, that perhaps could be better solved directly within KLayout?  The way you created KLayoutPCell looks reasonable to me.

Class Port - now is in utils/geometry.  Why not have it in SiEPIC/core.py, along side Net, Component, and Pin.  It seems like Port and Pin have the same functionality (direction, width, name) - redundant? What is the difference between a Pin and a Port?  By the way, I created a simple function to draw the pin geometry, to simplify the code: https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/commit/178150c72d10a849b3b6f33b1b5669e9a0b7e3a1

Next: testability of the code. we need scripts to verify that all the changes we make keep working.  both using external python, plus internal to KLayout.  e.g,. menu item in KLayout SiEPIC | Example Layouts - e.g., "Test all SiEPIC-Tools functionality"


... more thoughts later ...

cheers,
Lukas

**Comment by thomaslima** [comment]
I would like to provide a few answers to your questions before I have the change to look into it with more detail.

- That sounds good to target version 0.4.

- I haven’t been able to run it outside of klayout because of siepic. Simply importing siepic and using get_technology requires us to be inside klayout for the proper xml file loading. Plus, there are still a lot of references to pya.Application, which doesn’t exist in klayout.db

- I can provide an example of pcell for ebeam. In fact I should upgrade the pcell class to return more than ports but also more metadata so we can make changes in the future. I think this pcell shouldn’t belong to klayout, but be specific to siepic tools.

- I recognized I haven’t used the Pin class enough. I agree they should be merged. But ports are complex, they should identify more than name direction and width. They should have a connection to the kind of waveguide it connects to. Think of strip waveguide vs rib waveguide etc, dc trace vs Rf.

- I would like to use Alex’s approach as well as internal unit tests with 100% coverage to guarantee code will work.



On 12 Oct 2018, at 03:01, Lukas Chrostowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Thomas, @thomaslima<https://github.com/thomaslima> @jaspreetj<https://github.com/jaspreetj>

In response to: https://github.com/lightwave-lab/SiEPIC-Tools/blob/lightwave/SiEPIC-Tools%20refactoring.md

I created a new branch, v0.4.0, to begin the large project of refactoring. I moved your pull request to that branch so we can leave the v0.3.x alone for those that currently use it, and to use all your updates towards a major release. Does that sound good? We can work on the v0.4.0 branch between now and Dec 1st, then around then, move it back to master, and in KLayout Package manager point to the new v0.4.0…

How have you been using KLayout / SiEPIC-Tools lately? Do you run it within KLayout, or are you now able to run externally? In other words, have you done enough refactoring to make it work externally, or is that more of a wish at this stage?

class KLayoutPCell(object): you have examples of PCells? in SiEPIC_IME_Lightwave there is a ring filter, but I think it is outdated compared to the new one. Do you have any in EBeam too? I think it would be good to refactor some of the EBeam cells (since it is a public library), and provide a guideline of how people should create PCells from now. And also procedural layout examples. Hopefully it isn’t complicated.

We now have an AMF PDK and Library (two separate repositories), based on SiEPIC_IME. Layer tables are different, and we have AMF’s PDK (their components) loaded in.

I am also wondering if Matthias at KLayout should be involved. For example, your KLayoutPCell, and class IMECell(object), really are creating building on top of Matthias did, rather than fixing it directly. Are we creating too many layers of complexity, that perhaps could be better solved directly within KLayout? The way you created KLayoutPCell looks reasonable to me.

Class Port - now is in utils/geometry. Why not have it in SiEPIC/core.py, along side Net, Component, and Pin. It seems like Port and Pin have the same functionality (direction, width, name) - redundant? What is the difference between a Pin and a Port? By the way, I created a simple function to draw the pin geometry, to simplify the code: lukasc-ubc/SiEPIC_EBeam_PDK@178150c<https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/commit/178150c72d10a849b3b6f33b1b5669e9a0b7e3a1>

Next: testability of the code. we need scripts to verify that all the changes we make keep working. both using external python, plus internal to KLayout. e.g,. menu item in KLayout SiEPIC | Example Layouts - e.g., "Test all SiEPIC-Tools functionality"

... more thoughts later ...

cheers,
Lukas

**Pull request merged**
