### PR TITLE
initial draft of siepic_tools python package, refactoring guidelines

### PR DESCRIPTION
**Pull request by thomaslima**
@atait @jaspreetj @lukasc-ubc 

This is a big Pull request and I am sorry that I put my commits in the same branch that @atait was working on (`self-testing`).

As the title suggest, the purpose of this PR is to show you my suggestions for the refactoring of SiEPIC tools so it can become a pure python package that depends on the newly minted klayout package (now at version `0.26.0.dev10`).

The first step is to move everything related to layout (database objects, technology etc.) under `python/SiEPIC` to `python/siepic_tools`. You will see that I've transported most of SiEPIC.utils.* (my own code), and some of SiEPIC.extend, just enough so that https://github.com/lightwave-lab/SiEPIC_EBeam_PDK/tree/scripted_layout works. I am hoping that you can help me continue this work and finish the necessary refactoring.

I've also written some technology management functions in siepic_tools.utils.tech so that we can use `get_technology_by_name(name)` or `register_siepic_technology(lyt_filename)` directly from python. This way Libraries can be loaded and registered too.

For example, this is the code in `__init__.py` for `siepic_ebeam_pdk` module available above:

```python
from os.path import join
from siepic_tools.utils import register_siepic_technology as register

# Load technologies included in the pdk
tech_path = join('..', '..', 'klayout_dot_config', 'tech')
EBEAM_TECH = register(join(tech_path, 'EBeam', 'EBeam.lyt'))


# Load libraries
from .library import SiEPIC_EBeam  # noqa
SiEPIC_EBeam(verbose=False)
```

As you can see, it loads `EBEAM_TECH` and loads the library registering a few pcells. Very little refactoring done so far on these pcells. But what's important is that now we can load EBeam's technology and library just with `import siepic_ebeam_pdk`. Since this pdk can be a python package, we can make this pdk available in PyPI, and the same code will live in the salt package! Please look again at https://github.com/lukasc-ubc/SiEPIC-Tools/blob/self-testing/SiEPIC-Tools%20refactoring.md

Another TODO. All code in siepic_tools can now be unit-tested. I need help making some tests for it. I would make this a priority.

### CODE REVIEW

**Comment by thomaslima** [comment]
Another thing is that this package, for now, needs to be compatible with python2 and python3, because SiEPIC-Tools in klayout depends on it.

**Comment by lukasc-ubc** [comment]
Thank you Thomas. I have family holidays this coming week, and the start of term and two grants, the following week. Then edX starts on Jan 15. So realistically not much time coming up for me.

**Comment by thomaslima** [comment]
Thanks for letting me know. Time is short on our end too, that's why I only made minimal changes in order to use siepic tools properly with our scripts. I only ask that future changes in code take into account my refactoring so far, that is, include new cells in siepic_tools's library.py instead of the library macro. 

Are you opposed to me registering two python packages in pypi? one called siepic_tools and the other siepic_ebeam_pdk? This will make installation easier for my team.

**Comment by lukasc-ubc** [comment]
pypi packages: yes sounds good!

**Comment by lukasc-ubc** [comment]
@thomaslima 

@mustafacc and @lukasc-ubc  took the changes from "master" and "self-testing", and merged them into "0.4.0".

Things work within the KLayout GUI.

Next is to work on import siepic_tools, etc.

**Pull request merged**
